### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId" : 1,
  "accountNumber" : "1000000002",
  "amount" : 10000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId" : "c5389572cd8c4e289643bd74573a9c21",
  "accountNumber" : "1000000002",
  "amount" : 10000
}


### query transaction
GET http://localhost:8080/transaction/c5389572cd8c4e289643bd74573a9c21